import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Alert, Button, Card, Col, Input, Row, Select, Space, Steps, Tag, Typography } from 'antd';
import { BuildOutlined, ClockCircleOutlined, EnvironmentOutlined, HeartOutlined, HistoryOutlined, HomeOutlined, StarOutlined } from '@ant-design/icons';
import { visitorAPI, type AdvisoryProfile, type RoutePlanResponse, type RoutePlanningRequest } from '../../services/api';
import { openBaiduNavigation } from '../../utils/navigation';
import { getClarificationPrompt, getRouteOutcomeLabel, getRouteRejectionMessage, getRouteRequestLabel, getSceneExtractionNote, type RouteOutcome } from './route-outcome';

const { Title, Paragraph, Text } = Typography;
const SPOT_COORDS: Record<string, { lat: number; lng: number }> = {
  '景区南门': { lat: 31.42190, lng: 120.09720 }, '灵山大照壁': { lat: 31.42250, lng: 120.09740 }, '五明桥': { lat: 31.42240, lng: 120.09740 }, '佛足坛': { lat: 31.42330, lng: 120.09700 }, '五智门': { lat: 31.42460, lng: 120.09630 }, '菩提大道': { lat: 31.42400, lng: 120.09670 }, '九龙灌浴': { lat: 31.42662, lng: 120.09523 }, '降魔浮雕': { lat: 31.42500, lng: 120.09610 }, '阿育王柱': { lat: 31.42530, lng: 120.09590 }, '百子戏弥勒': { lat: 31.42540, lng: 120.09760 }, '祥符禅寺': { lat: 31.42986, lng: 120.09309 }, '灵山大佛': { lat: 31.43205, lng: 120.09151 }, '佛教文化博览馆': { lat: 31.43205, lng: 120.09151 }, '灵山梵宫': { lat: 31.43065, lng: 120.09756 }, '五印坛城': { lat: 31.42664, lng: 120.09813 }, '曼飞龙塔': { lat: 31.42800, lng: 120.09900 }, '无尽意斋': { lat: 31.43050, lng: 120.09180 }, '拈花广场': { lat: 31.41780, lng: 120.06950 }, '梵天花海': { lat: 31.41960, lng: 120.07620 }, '香月花街': { lat: 31.41950, lng: 120.07080 }, '拈花堂': { lat: 31.42120, lng: 120.07220 }, '五灯湖': { lat: 31.42000, lng: 120.07280 }, '鹿鸣谷': { lat: 31.42430, lng: 120.07630 },
};
const SPOT_IMAGES: Record<string, string> = { '景区南门': 'shengjing_gate.jpg', '灵山大照壁': 'lingshan_zhaobi.jpg', '五明桥': 'wuming_bridge.jpg', '佛足坛': 'fozu_altar.jpg', '五智门': 'wuzhi_gate.jpg', '菩提大道': 'puti_avenue.jpg', '九龙灌浴': 'jiulong_guanyu.jpg', '降魔浮雕': 'xiangmo_relief.jpg', '阿育王柱': 'ayuwang_pillar.jpg', '百子戏弥勒': 'baiziximile.jpg', '祥符禅寺': 'xiangfu_temple.jpg', '灵山大佛': 'lingshan_dafo.jpg', '佛教文化博览馆': 'fojiao_museum.jpg', '灵山梵宫': 'lingshan_fangong.jpg', '五印坛城': 'wuyin_tancheng.jpg', '曼飞龙塔': 'manfeilong_pagoda.jpg', '无尽意斋': 'https://www.xiangfusi.com/UploadImages/image/201805251612383590.jpg', '拈花广场': 'nianhua_square.jpg', '梵天花海': 'fantian_huahai.jpg', '香月花街': 'xiangyue_street.jpg', '拈花堂': 'nianhua_hall.jpg', '五灯湖': 'wuhu_lamp.jpg', '鹿鸣谷': 'luming_valley.jpg' };
const interests = [
  { key: '历史', icon: <HistoryOutlined />, label: '历史文化', desc: '千年佛教传承' }, { key: '文化', icon: <StarOutlined />, label: '佛教文化', desc: '深度文化体验' }, { key: '自然', icon: <EnvironmentOutlined />, label: '自然风光', desc: '太湖山水美景' }, { key: '建筑', icon: <BuildOutlined />, label: '建筑艺术', desc: '佛教建筑杰作' }, { key: '祈福', icon: <HeartOutlined />, label: '祈福体验', desc: '吉祥平安之旅' },
];
const defaultQuery = '我带腿脚不方便的妈妈，现在在景区入口，只有三小时，还想看两点的《吉祥颂》，应该怎么走？';

export default function RecommendPage() {
  const navigate = useNavigate();
  const [selected, setSelected] = useState<string[]>([]);
  const [duration, setDuration] = useState(4);
  const [travelType, setTravelType] = useState('朋友');
  const [ageGroup, setAgeGroup] = useState<AdvisoryProfile['ageGroup']>('青年');
  const [budget, setBudget] = useState<AdvisoryProfile['budget']>('舒适型');
  const currentLocation = 'south_gate';
  const currentTime = '09:00';
  const mobility = 'normal' as const;
  const pace = 'normal' as const;
  const [sceneQuery, setSceneQuery] = useState(defaultQuery);
  const [sceneRoute, setSceneRoute] = useState<RoutePlanResponse | null>(null);
  const [routeOrigin, setRouteOrigin] = useState<'natural' | 'interest'>('natural');
  const [loading, setLoading] = useState(false);
  const [clarificationInput, setClarificationInput] = useState('');

  const submitRoute = async (request: RoutePlanningRequest, origin: 'natural' | 'interest') => { setRouteOrigin(origin); setSceneRoute(null); setLoading(true); try { setSceneRoute((await visitorAPI.planRoute(request)).data); } catch (error) { console.error('Route planning error:', error); } finally { setLoading(false); } };
  const handleRecommend = () => submitRoute({ scene_state: { currentLocation, currentTime, remainingMinutes: duration * 60, partyType: travelType, mobility, pace, interests: [...selected], mustVisitSpotIds: [], preferredPerformanceIds: [], visitedSpotIds: [] }, advisory_profile: { ageGroup, budget } }, 'interest');
  const handleScenePlan = (query = sceneQuery) => { if (query.trim()) void submitRoute({ query }, 'natural'); };
  const handleClarification = () => { const extra = clarificationInput.trim(); if (!extra) return; const query = `${sceneQuery.trim()}，${extra}`; setSceneQuery(query); setClarificationInput(''); handleScenePlan(query); };
  const toggleInterest = (key: string) => setSelected(previous => previous.includes(key) ? previous.filter(item => item !== key) : [...previous, key]);

  const steps = sceneRoute?.route?.steps ?? [];
  const names = steps.map((step, index) => sceneRoute?.evidence?.[index]?.name || step.spotId);
  const outcome = (sceneRoute?.outcome ?? (sceneRoute?.feasibility ? 'feasible' : 'infeasible')) as RouteOutcome;
  const adjusted = outcome === 'feasible_with_rejected_preferences' && steps.length > 0;
  const feasible = outcome === 'feasible' && steps.length > 0;
  const missing = Array.from(new Set([...(sceneRoute?.scene_state?.missingCriticalFields ?? []), ...(sceneRoute?.scene_extraction?.missingFields ?? [])]));
  const clarificationPrompts = missing.map(getClarificationPrompt).filter(prompt => prompt !== '请补充相关游览信息。');
  const clarification = sceneRoute?.clarification || sceneRoute?.explanation?.clarification || (clarificationPrompts.length ? [...new Set(clarificationPrompts)].join(' ') : undefined);
  const rejected = sceneRoute?.route?.rejectedRequests ?? sceneRoute?.explanation?.rejected_requests ?? [];
  const inputEffects = sceneRoute?.explanation?.input_effects?.filter(effect => effect.applied) ?? [];

  return <div style={{ minHeight: '100vh', background: '#f5f5f5' }}>
    <div style={{ background: 'linear-gradient(135deg, #c41d7f 0%, #e91e63 100%)', padding: 20, textAlign: 'center', color: '#fff', boxShadow: '0 2px 8px rgba(0,0,0,0.15)' }}><Button type="text" icon={<HomeOutlined />} onClick={() => navigate('/')} style={{ color: '#fff', position: 'absolute', left: 16, top: 20 }} /><Title level={3} style={{ color: '#fff', margin: 0 }}>🗺️ 个性化游览推荐</Title></div>
    <div style={{ maxWidth: 1000, margin: '0 auto', padding: '24px 20px', display: 'flex', flexDirection: 'column' }}>
      <Card title="🧭 按你的情况规划路线" style={{ borderRadius: 16, marginBottom: 20, border: 'none', boxShadow: '0 2px 12px rgba(0,0,0,0.06)' }}><Paragraph type="secondary">告诉我你现在在哪里、还剩多久、和谁一起，我会先确认时间是否来得及，再为你安排路线。</Paragraph><Input.TextArea value={sceneQuery} onChange={event => setSceneQuery(event.target.value)} autoSize={{ minRows: 2, maxRows: 4 }} placeholder={defaultQuery} /><div style={{ textAlign: 'center', marginTop: 16 }}><Button type="primary" onClick={() => handleScenePlan()} loading={loading} disabled={!sceneQuery.trim()}>帮我规划路线</Button></div></Card>

      <Card title="选择您的兴趣偏好" style={{ order: 3, borderRadius: 16, marginBottom: 20, border: 'none', boxShadow: '0 2px 12px rgba(0,0,0,0.06)' }}><Row gutter={[12, 12]}>{interests.map(item => <Col xs={12} sm={8} md={8} lg={8} key={item.key}><Card hoverable onClick={() => toggleInterest(item.key)} style={{ borderRadius: 12, textAlign: 'center', border: selected.includes(item.key) ? '2px solid #c41d7f' : '1px solid #f0f0f0', background: selected.includes(item.key) ? '#fdf2f8' : '#fff' }}><div style={{ fontSize: 28, color: '#c41d7f', marginBottom: 8 }}>{item.icon}</div><div style={{ fontWeight: 600 }}>{item.label}</div><div style={{ fontSize: 12, color: '#999' }}>{item.desc}</div></Card></Col>)}</Row><div style={{ marginTop: 20, textAlign: 'center' }}><Space wrap size={12}><Text>出行类型：</Text><Select value={travelType} onChange={setTravelType} style={{ width: 110 }} options={['朋友', '情侣', '亲子', '带长辈'].map(value => ({ value, label: value }))} /><Text>年龄段：</Text><Select value={ageGroup} onChange={setAgeGroup} style={{ width: 110 }} options={['青年', '中年', '老年'].map(value => ({ value, label: value }))} /><Text>预算类型：</Text><Select value={budget} onChange={setBudget} style={{ width: 110 }} options={['经济型', '舒适型', '豪华型'].map(value => ({ value, label: value }))} /></Space></div><div style={{ marginTop: 20, textAlign: 'center' }}><Text>预计游览时长：</Text>{[3, 4, 5, 6].map(hours => <Tag key={hours} color={duration === hours ? 'magenta' : 'default'} style={{ cursor: 'pointer', margin: '0 4px', padding: '4px 16px', borderRadius: 16 }} onClick={() => setDuration(hours)}><ClockCircleOutlined /> {hours} 小时</Tag>)}</div><div style={{ marginTop: 18, textAlign: 'center', color: '#888', fontSize: 13 }}>位置、时间、行动能力和节奏会参与路线计算；年龄与预算只影响个性化提示。</div><div style={{ textAlign: 'center', marginTop: 24 }}><Button type="primary" size="large" onClick={() => handleRecommend()} loading={loading} disabled={selected.length === 0} style={{ background: 'linear-gradient(135deg, #c41d7f, #e91e63)', border: 'none', height: 48, borderRadius: 24, paddingInline: 40 }}>生成推荐路线</Button></div></Card>

      {sceneRoute && <Card title={feasible || adjusted ? '✨ 推荐路线' : '⚠️ 路线安排提示'} style={{ order: routeOrigin === 'interest' ? 4 : 2, borderRadius: 16, border: 'none', boxShadow: '0 2px 12px rgba(0,0,0,0.06)' }} className="fade-in"><div style={{ marginBottom: 16, padding: '12px 16px', background: '#fdf2f8', borderRadius: 12 }}><Space size={6} wrap><Tag color={feasible ? 'green' : adjusted ? 'gold' : 'orange'} style={{ borderRadius: 12 }}>{getRouteOutcomeLabel(outcome, steps.length)}</Tag><Tag color="cyan" style={{ borderRadius: 12 }}>总游览时长：{sceneRoute.route?.totalMinutes ?? 0} 分钟</Tag><Tag>步行 {sceneRoute.route?.walkingMinutes ?? 0} 分钟</Tag><Tag>游览 {sceneRoute.route?.visitingMinutes ?? 0} 分钟</Tag>{(sceneRoute.route?.waitingMinutes ?? 0) > 0 && <Tag>等待 {sceneRoute.route?.waitingMinutes ?? 0} 分钟</Tag>}</Space>{getSceneExtractionNote(sceneRoute.scene_extraction) && <Alert style={{ marginTop: 12 }} type="info" message={getSceneExtractionNote(sceneRoute.scene_extraction)} />}{inputEffects.length > 0 && <Text type="secondary" style={{ display: 'block', marginTop: 10 }}>{inputEffects.map(effect => effect.summary).join('；')}</Text>}{sceneRoute.explanation?.route_rationale?.length ? <Text type="secondary" style={{ display: 'block', marginTop: 4 }}>{sceneRoute.explanation.route_rationale.join('；')}</Text> : null}{sceneRoute.explanation?.consumer_advice?.length ? <Text type="secondary" style={{ display: 'block', marginTop: 4 }}>{sceneRoute.explanation.consumer_advice.join('；')}</Text> : null}</div>{clarification && <Space direction="vertical" style={{ width: '100%', marginBottom: 16 }} size={10}><Alert type="warning" message="还需要补充一点信息" description={clarification} /><Space.Compact block><Input aria-label="路线补充信息" value={clarificationInput} onChange={event => setClarificationInput(event.target.value)} onPressEnter={handleClarification} placeholder="例如：现在上午10点" /><Button type="primary" onClick={handleClarification} disabled={!clarificationInput.trim()} loading={loading}>补充并重新规划</Button></Space.Compact></Space>}{rejected.length > 0 && <Alert style={{ marginBottom: 16 }} type="info" message="有一项安排暂时无法加入路线" description={rejected.map(item => `${getRouteRequestLabel(item.item)}：${getRouteRejectionMessage(item.reasonCode)}`).join('；')} />}
        <Row gutter={[16, 16]}><Col xs={24} lg={13}><Steps direction="vertical" current={-1} items={steps.map((item, index) => { const name = names[index] || '下一站'; const coords = SPOT_COORDS[name]; return { title: <Text strong>{item.performanceId ? `${item.start}–${item.end} 观看${item.performanceName || '目标演出'}` : `${item.start}–${item.end} ${name}`}</Text>, description: <div><Paragraph type="secondary" style={{ marginBottom: 4 }}>{item.arrive} 到达{name}，步行 {item.walkMinutes} 分钟{item.waitingMinutes ? `，等待 ${item.waitingMinutes} 分钟后观看` : `，停留 ${item.visitMinutes} 分钟`}</Paragraph><Tag color="magenta" style={{ borderRadius: 12 }}>⏱️ {item.visitMinutes}分钟</Tag>{coords && <Button type="link" onClick={() => openBaiduNavigation(coords, name)}>🚗 到这里</Button>}</div>, icon: <div style={{ width: 28, height: 28, borderRadius: '50%', background: 'linear-gradient(135deg, #c41d7f, #e91e63)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, fontWeight: 700 }}>{index + 1}</div> }; })} /></Col><Col xs={24} lg={11}><div style={{ background: '#fafafa', border: '1px solid #f0f0f0', borderRadius: 12, padding: '16px 20px' }}>{names.map((name, index) => <div key={`${name}-${index}`} style={{ display: 'flex', gap: 14 }}><div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}><div style={{ width: 28, height: 28, borderRadius: '50%', background: 'linear-gradient(135deg, #c41d7f, #e91e63)', color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13, fontWeight: 700 }}>{index + 1}</div>{index < names.length - 1 && <div style={{ width: 2, flex: 1, background: '#e0c7d8', margin: '4px 0' }} />}</div><div style={{ paddingBottom: index < names.length - 1 ? 20 : 0, flex: 1 }}><div style={{ fontWeight: 600, marginBottom: 6 }}>{name}</div>{SPOT_IMAGES[name] ? <img src={`/${SPOT_IMAGES[name]}`} alt={name} style={{ width: '100%', maxWidth: 240, height: 120, objectFit: 'cover', borderRadius: 8 }} /> : <div style={{ color: '#bbb', fontSize: 12 }}>暂无图片</div>}</div></div>)}</div></Col></Row><div style={{ textAlign: 'center', marginTop: 20 }}><Button type="primary" onClick={() => navigate('/qa')} style={{ background: 'linear-gradient(135deg, #c41d7f, #e91e63)', border: 'none', borderRadius: 20 }}>开始游览，了解更多景点详情</Button></div></Card>}
    </div>
  </div>;
}
